### ISSUE TITLE
About the code release

### ISSUE THREAD

**Issue by ruili3** [haotian-liu/MaskPoint#1]
Hi,

I read the paper and the idea is quite impressive!

Since sharing the complete training & testing code takes time, can you share the architectures of the network for a first glance? We're conducting some related research and wish to learn from it. 

Thanks!

**Comment by haotian-liu** [comment]
Sorry for the late reply -- I somehow missed this issue.  We have just released the code and the checkpoints.

And for the architecture of the backbone, we mainly follow the Point-BERT design with plain Transformers for a fair comparison.

**Comment by WWW2323** [comment]
@haotian-liu hi, thanks for your codes very much! And, when will the codes about ScanNetV2 come? thanks~

**Comment by haotian-liu** [comment]
@WWW2323  Thank you for your interest in our project.  Our plan is to release the ScanNetV2 code and checkpoints by early next week.

**Comment by haotian-liu** [comment]
@WWW2323 The 3D object detection code has just been released :)

**Comment by WWW2323** [comment]
Great! And, how long did you train 3detr?  Did you use only one GPU to train 3detr for 1080 epochs? It seems to need a week for me,  orz
