### ISSUE TITLE
ScanNet-Medium

### ISSUE THREAD

**Issue by RunpeiDong** [haotian-liu/MaskPoint#3]
Dear authors,

Thanks for your great work! The "ScanNet-Medium" is generated by sampling every 10 frames, which is claimed to be smaller (\~**25K** samples) than DepthContrast (\~**190K**). However, the sampling rate used by DepthContrast is **15** which is larger than **10**. Can you kindly tell me why the ScanNet-Medium is smaller?

Regards

**Comment by haotian-liu** [comment]
Hi @RunpeiDong 

Thank you for your interest in our work.  DepthContrast sub-sampled ScanNet with a sampling rate of 10 [here](https://github.com/facebookresearch/DepthContrast/blob/main/data/scannet/extract_pointcloud.py#L45).  We further downsample DepthContrast subset with a sampling rate of 10, i.e. we generate a sub-sampled ScanNet with an effective sampling rate of 100, resulting in ~25K samples.

**Comment by RunpeiDong** [comment]
Hi @haotian-liu 

Thanks very much for the answer, it makes sense.

Regards
